### ISSUE TITLE
AttributeError: module 'databuild' has no attribute 'readDMV'

### ISSUE THREAD

**Issue by PriyaShaji** [MODA-NYC/Project_SevereCrashes#1]
Hi,

I was executing file `DataDetail.ipynb`, but I was getting error while running `crash,ind,veh = db.readDMV()`

Error: `AttributeError: module 'databuild' has no attribute 'readDMV`

It gives same error with python2 and python3 kernel. data build version is 0.0.10

Any help is appreciated.

**Comment by deenapatel** [comment]
Hi Priya,

db.readDMV() is a method that read from a city database. You'd have to 
replace that with reading in the data from a file. The State DMV gave me 
those data files, but we were not allowed to share them with the public 
unfortunately.

Alot of that same data is now available on NYC open data, but it's not in 
the exact same format (field names are different, etc). So you'd really 
have to recreate the analysis from scratch.

Deena

**Comment by PriyaShaji** [comment]
Okay, I will try from NYC open datasets.

Thank you for your help.
